name: mvvm_cli_nerdzlab
description: MVVM CLI Tool, a command-line utility designed to streamline the creation of MVVM projects.
version: 1.0.0
repository: https://github.com/nerdzlab/NerdzFlutter-MVVMCli

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dcli: ^6.1.0
  path: ^1.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  mvvm: mvvm_cli_nerdzlab